version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    redis0:
        image: redis
        command:
            - --port
            - '6000'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis1:
        image: redis
        command:
            - --port
            - '6001'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis2:
        image: redis
        command:
            - --port
            - '6002'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis3:
        image: redis
        command:
            - --port
            - '6003'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis4:
        image: redis
        command:
            - --port
            - '6004'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis5:
        image: redis
        command:
            - --port
            - '6005'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis6:
        image: redis
        command:
            - --port
            - '6006'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis7:
        image: redis
        command:
            - --port
            - '6007'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    redis8:
        image: redis
        command:
            - --port
            - '6008'
            - --cluster-enabled
            - 'yes'
            - --maxmemory
            - 100mb
        network_mode: host
    manager:
      image: eirsyl/apollo:latest
      command: manager
      network_mode: host
    agent0:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6000 --managerTLS=false
      network_mode: host
    agent1:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6001 --managerTLS=false
      network_mode: host
    agent2:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6002 --managerTLS=false
      network_mode: host
    agent3:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6003 --managerTLS=false
      network_mode: host
    agent4:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6004 --managerTLS=false
      network_mode: host
    agent5:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6005 --managerTLS=false
      network_mode: host
    agent6:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6006 --managerTLS=false
      network_mode: host
    agent7:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6007 --managerTLS=false
      network_mode: host
    agent8:
      image: eirsyl/apollo:latest
      command: agent --redis=127.0.0.1:6008 --managerTLS=false
      network_mode: host
    prometheus:
        image: prom/prometheus
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
        network_mode: host
    grafana:
        image: grafana/grafana
        depends_on:
          - prometheus
        network_mode: host
        volumes:
          - grafana_data:/var/lib/grafana
