// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StateRequest struct {
	IsEmpty         bool              `protobuf:"varint,1,opt,name=isEmpty" json:"isEmpty,omitempty"`
	Nodes           []*ClusterNode    `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	HostAnnotations []*HostAnnotation `protobuf:"bytes,3,rep,name=hostAnnotations" json:"hostAnnotations,omitempty"`
	Metrics         []*NodeMetric     `protobuf:"bytes,4,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *StateRequest) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

func (m *StateRequest) GetNodes() []*ClusterNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *StateRequest) GetHostAnnotations() []*HostAnnotation {
	if m != nil {
		return m.HostAnnotations
	}
	return nil
}

func (m *StateRequest) GetMetrics() []*NodeMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type StateResponse struct {
	Ack bool `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StateResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

// *
// TYPES
type ClusterNode struct {
	NodeID      string   `protobuf:"bytes,1,opt,name=nodeID" json:"nodeID,omitempty"`
	Addr        string   `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Flags       string   `protobuf:"bytes,3,opt,name=flags" json:"flags,omitempty"`
	Role        string   `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	Myself      bool     `protobuf:"varint,5,opt,name=myself" json:"myself,omitempty"`
	MasterID    string   `protobuf:"bytes,6,opt,name=masterID" json:"masterID,omitempty"`
	PingSent    int64    `protobuf:"varint,7,opt,name=pingSent" json:"pingSent,omitempty"`
	PingRecv    int64    `protobuf:"varint,8,opt,name=pingRecv" json:"pingRecv,omitempty"`
	ConfigEpoch int64    `protobuf:"varint,9,opt,name=configEpoch" json:"configEpoch,omitempty"`
	LinkStatus  string   `protobuf:"bytes,10,opt,name=linkStatus" json:"linkStatus,omitempty"`
	Slots       []string `protobuf:"bytes,11,rep,name=slots" json:"slots,omitempty"`
}

func (m *ClusterNode) Reset()                    { *m = ClusterNode{} }
func (m *ClusterNode) String() string            { return proto.CompactTextString(m) }
func (*ClusterNode) ProtoMessage()               {}
func (*ClusterNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ClusterNode) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *ClusterNode) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ClusterNode) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *ClusterNode) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ClusterNode) GetMyself() bool {
	if m != nil {
		return m.Myself
	}
	return false
}

func (m *ClusterNode) GetMasterID() string {
	if m != nil {
		return m.MasterID
	}
	return ""
}

func (m *ClusterNode) GetPingSent() int64 {
	if m != nil {
		return m.PingSent
	}
	return 0
}

func (m *ClusterNode) GetPingRecv() int64 {
	if m != nil {
		return m.PingRecv
	}
	return 0
}

func (m *ClusterNode) GetConfigEpoch() int64 {
	if m != nil {
		return m.ConfigEpoch
	}
	return 0
}

func (m *ClusterNode) GetLinkStatus() string {
	if m != nil {
		return m.LinkStatus
	}
	return ""
}

func (m *ClusterNode) GetSlots() []string {
	if m != nil {
		return m.Slots
	}
	return nil
}

type HostAnnotation struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *HostAnnotation) Reset()                    { *m = HostAnnotation{} }
func (m *HostAnnotation) String() string            { return proto.CompactTextString(m) }
func (*HostAnnotation) ProtoMessage()               {}
func (*HostAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *HostAnnotation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HostAnnotation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NodeMetric struct {
	Name  string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *NodeMetric) Reset()                    { *m = NodeMetric{} }
func (m *NodeMetric) String() string            { return proto.CompactTextString(m) }
func (*NodeMetric) ProtoMessage()               {}
func (*NodeMetric) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *NodeMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeMetric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*StateRequest)(nil), "api.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "api.StateResponse")
	proto.RegisterType((*ClusterNode)(nil), "api.ClusterNode")
	proto.RegisterType((*HostAnnotation)(nil), "api.HostAnnotation")
	proto.RegisterType((*NodeMetric)(nil), "api.NodeMetric")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	ReportState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) ReportState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/api.Manager/ReportState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	ReportState(context.Context, *StateRequest) (*StateResponse, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Manager/ReportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ReportState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportState",
			Handler:    _Manager_ReportState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xd4, 0x40,
	0x0c, 0x26, 0x9b, 0xfd, 0xab, 0x43, 0x69, 0x31, 0x08, 0x8d, 0x7a, 0x40, 0x21, 0x07, 0xb4, 0x5c,
	0xf6, 0x50, 0xa4, 0x1e, 0x90, 0x38, 0x54, 0xb4, 0x12, 0x3d, 0x94, 0xc3, 0xf4, 0x09, 0x86, 0xac,
	0x77, 0x1b, 0x35, 0x99, 0x19, 0x32, 0x93, 0x4a, 0x7d, 0x22, 0xde, 0x81, 0xa7, 0x43, 0x76, 0xb2,
	0x6d, 0xca, 0x85, 0x9b, 0xbf, 0xef, 0xf3, 0x37, 0xf6, 0xd8, 0x86, 0xc3, 0xc6, 0x58, 0xb3, 0xa3,
	0x76, 0xed, 0x5b, 0x17, 0x1d, 0xa6, 0xc6, 0x57, 0xc5, 0x9f, 0x04, 0x5e, 0xde, 0x44, 0x13, 0x49,
	0xd3, 0xaf, 0x8e, 0x42, 0x44, 0x05, 0x8b, 0x2a, 0x5c, 0x36, 0x3e, 0x3e, 0xa8, 0x24, 0x4f, 0x56,
	0x4b, 0xbd, 0x87, 0xf8, 0x11, 0x66, 0xd6, 0x6d, 0x28, 0xa8, 0x49, 0x9e, 0xae, 0xb2, 0xd3, 0xe3,
	0xb5, 0xf1, 0xd5, 0xfa, 0x5b, 0xdd, 0x85, 0x48, 0xed, 0x0f, 0xb7, 0x21, 0xdd, 0xcb, 0xf8, 0x15,
	0x8e, 0x6e, 0x5d, 0x88, 0xe7, 0xd6, 0xba, 0x68, 0x62, 0xe5, 0x6c, 0x50, 0xa9, 0x38, 0xde, 0x88,
	0xe3, 0xfb, 0x33, 0x4d, 0xff, 0x9b, 0x8b, 0x9f, 0x60, 0xd1, 0x50, 0x6c, 0xab, 0x32, 0xa8, 0xa9,
	0xd8, 0x8e, 0xc4, 0xc6, 0x15, 0xae, 0x85, 0xd7, 0x7b, 0xbd, 0xf8, 0x00, 0x87, 0x43, 0xef, 0xc1,
	0x3b, 0x1b, 0x08, 0x8f, 0x21, 0x35, 0xe5, 0xdd, 0xd0, 0x38, 0x87, 0xc5, 0xef, 0x09, 0x64, 0xa3,
	0x1e, 0xf1, 0x1d, 0xcc, 0xb9, 0xcb, 0xab, 0x0b, 0x49, 0x3a, 0xd0, 0x03, 0x42, 0x84, 0xa9, 0xd9,
	0x6c, 0x5a, 0x35, 0x11, 0x56, 0x62, 0x7c, 0x0b, 0xb3, 0x6d, 0x6d, 0x76, 0xdc, 0x3e, 0x93, 0x3d,
	0xe0, 0xcc, 0xd6, 0xd5, 0xa4, 0xa6, 0x7d, 0x26, 0xc7, 0xfc, 0x6a, 0xf3, 0x10, 0xa8, 0xde, 0xaa,
	0x99, 0x94, 0x1e, 0x10, 0x9e, 0xc0, 0xb2, 0x31, 0x5c, 0xfb, 0xea, 0x42, 0xcd, 0x25, 0xff, 0x11,
	0xb3, 0xe6, 0x2b, 0xbb, 0xbb, 0x21, 0x1b, 0xd5, 0x22, 0x4f, 0x56, 0xa9, 0x7e, 0xc4, 0x7b, 0x4d,
	0x53, 0x79, 0xaf, 0x96, 0x4f, 0x1a, 0x63, 0xcc, 0x21, 0x2b, 0x9d, 0xdd, 0x56, 0xbb, 0x4b, 0xef,
	0xca, 0x5b, 0x75, 0x20, 0xf2, 0x98, 0xc2, 0xf7, 0x00, 0x75, 0x65, 0xef, 0x78, 0x34, 0x5d, 0x50,
	0x20, 0x75, 0x47, 0x0c, 0xff, 0x2b, 0xd4, 0x2e, 0x06, 0x95, 0xe5, 0x29, 0xff, 0x4b, 0x40, 0xf1,
	0x05, 0x5e, 0x3d, 0x5f, 0x0d, 0xff, 0xd4, 0x9a, 0x86, 0x86, 0x49, 0x49, 0xcc, 0xde, 0x7b, 0x53,
	0x77, 0x34, 0x0c, 0xaa, 0x07, 0xc5, 0x19, 0xc0, 0xd3, 0x7e, 0xfe, 0xef, 0x4b, 0x06, 0xdf, 0xe9,
	0x39, 0x2c, 0xae, 0xfb, 0x9b, 0xc4, 0x33, 0xc8, 0x34, 0x79, 0xd7, 0x46, 0xd9, 0x28, 0xbe, 0x96,
	0xa5, 0x8f, 0x2f, 0xf3, 0x04, 0xc7, 0x54, 0xbf, 0xf0, 0xe2, 0xc5, 0xcf, 0xb9, 0x1c, 0xf3, 0xe7,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xf4, 0x57, 0x59, 0xdd, 0x02, 0x00, 0x00,
}
