version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/eirsyl/apollo
    steps:
      - checkout
      - run:
          name: test
          command: make test
          no_output_timeout: 20m
