global:
  evaluation_interval: 10s
  external_labels:
      monitor: 'apollo'

scrape_configs:
  - job_name: 'apollo-agent'
    scrape_interval: 5s
    static_configs:
      - targets:
        - '127.0.0.1:8000'
        - '127.0.0.1:8001'
        - '127.0.0.1:8002'
        - '127.0.0.1:8003'
        - '127.0.0.1:8004'
        - '127.0.0.1:8005'
        - '127.0.0.1:8006'
        - '127.0.0.1:8007'
        - '127.0.0.1:8008'

  - job_name: 'apollo-manager'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8000']

