{
 "title": "Bolt",
 "description": "BoltDB",
 "tags": [ "bolt" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Freelist Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bolt_freelist_alloc{job=\"apollo-manager\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "bolt_freelist_in_use{job=\"apollo-manager\"}",
     "legendFormat": "bytes used"
    }
   ]
  },
  {
   "title": "Freelist Pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bolt_free_page_n{job=\"apollo-manager\"}",
     "legendFormat": "free pages"
    },
    {
     "expr": "bolt_pending_page_n{job=\"apollo-manager\"}",
     "legendFormat": "pending pages"
    },
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(bolt_transactions{job=\"apollo-manager\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "bolt_open_transactions{job=\"apollo-manager\"}",
     "legendFormat": "open"
    }
   ]
  }
 ]
}