{
 "title": "GRPC Server",
 "tags": [ "grpc" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(grpc_server_started_total, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unary request error percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)\n / \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_type=\"unary\"}[1m])) by (grpc_service)\n * 100.0"
    }
   ]
  },
  {
   "title": "Average response stream size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{job=\"$job\",grpc_type=\"server_stream\"}[10m])) by (grpc_service)\n /\nsum(rate(grpc_server_started_total{job=\"$job\",grpc_type=\"server_stream\"}[10m])) by (grpc_service)"
    }
   ]
  },
  {
   "title": "Request inbound rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[1m])) by (grpc_service, instance)\n",
     "legendFormat": "{{instance}} {{grpc_service}}"
    }
   ]
  },
  {
   "title": "Unary request error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)\n"
    }
   ]
  }
 ]
}